#!/bin/sh


OUTPUT="random_1M2M"
echo " " > $OUTPUT
echo ============= >> $OUTPUT
./Seq/bicc_s 0 1048576 2097152 | grep METRICS >> $OUTPUT
for i in  2 4 6 8 10 12
do
   echo $i
   echo $i >>$OUTPUT
   bicc -t $i -- 0 1048576 2097152 | grep METRICS >>$OUTPUT 
done

echo "    " >>$OUTPUT
OUTPUT="random_1M4M"
echo " " > $OUTPUT
echo ============= >> $OUTPUT
./Seq/bicc_s 0 1048576 4194304 | grep METRICS >> $OUTPUT
for i in  2 4 6 8 10 12
do
   echo $i
   echo $i >>$OUTPUT
   bicc -t $i -- 0 1048576 4194304 | grep METRICS >>$OUTPUT 
done
echo "    " >>$OUTPUT

OUTPUT="random_1M6M"
echo " " > $OUTPUT
echo ============= >> $OUTPUT
./Seq/bicc_s 0 1048576 6291456 | grep METRICS >> $OUTPUT
for i in  2 4 6 8 10 12
do
   echo $i
   echo $i >>$OUTPUT
   bicc -t $i -- 0 1048576 6291456 | grep METRICS >>$OUTPUT 
done
echo "    " >>$OUTPUT

OUTPUT="random_1M10M"
echo " " > $OUTPUT
./Seq/bicc_s 0 1048576 10485760 | grep METRICS >> $OUTPUT
echo ============= >> $OUTPUT
for i in  2 4 6 8 10 12
do
   echo $i
   echo $i >>$OUTPUT
   bicc -t $i -- 0 1048576 10485760 | grep METRICS >>$OUTPUT 
done
echo "    " >>$OUTPUT

OUTPUT="random_1M20M"
echo " " > $OUTPUT
echo ============= >> $OUTPUT
./Seq/bicc_s 0 1048576 20971520 | grep METRICS >> $OUTPUT
for i in  2 4 6 8 10 12
do
   echo $i
   echo $i >>$OUTPUT
   bicc -t $i -- 0 1048576 20971520 | grep METRICS >>$OUTPUT 
done
echo "    " >>$OUTPUT
