#!/bin/sh

OUTPUT="breakdown_12threads"
echo "" >$OUTPUT
echo " " >> $OUTPUT
echo "=============" >> $OUTPUT
echo "12 THREADS are used"  >>$OUTPUT
echo "1M4M" >>$OUTPUT
   bicc -t 12 -- 0 1048576 4194304 | grep METRICS >>$OUTPUT 
echo "1M6M" >>$OUTPUT
   bicc -t 12 -- 0 1048576 6291456 | grep METRICS >>$OUTPUT 
echo "1M10M" >>$OUTPUT
   bicc -t 12 -- 0 1048576 10485760 | grep METRICS >>$OUTPUT 
echo "1M20M" >>$OUTPUT
   bicc -t 12 -- 0 1048576 20971520 | grep METRICS >>$OUTPUT 
echo "    " >>$OUTPUT
